// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMnjnZX7STL7yWkN8lG3jdX0LSw23rq8',
    appId: '1:940980520311:web:e5619a7468e7b372144d72',
    messagingSenderId: '940980520311',
    projectId: 'student-web-application',
    authDomain: 'student-web-application.firebaseapp.com',
    storageBucket: 'student-web-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFXHRySaabF_VR9EuQYzOLitFWIVMl_E',
    appId: '1:940980520311:android:dce242fa15ae78ca144d72',
    messagingSenderId: '940980520311',
    projectId: 'student-web-application',
    storageBucket: 'student-web-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUBbS3-cH5uLICxjUsfsto_N-aFcYS_c',
    appId: '1:940980520311:ios:a3fcd1c28e0b8f47144d72',
    messagingSenderId: '940980520311',
    projectId: 'student-web-application',
    storageBucket: 'student-web-application.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDUBbS3-cH5uLICxjUsfsto_N-aFcYS_c',
    appId: '1:940980520311:ios:a3fcd1c28e0b8f47144d72',
    messagingSenderId: '940980520311',
    projectId: 'student-web-application',
    storageBucket: 'student-web-application.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqMnjnZX7STL7yWkN8lG3jdX0LSw23rq8',
    appId: '1:940980520311:web:975030eebe98a304144d72',
    messagingSenderId: '940980520311',
    projectId: 'student-web-application',
    authDomain: 'student-web-application.firebaseapp.com',
    storageBucket: 'student-web-application.appspot.com',
  );
}
